# Generated by Django 3.1.2 on 2020-11-22 21:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20201122_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 22, 21, 52, 59, 821505, tzinfo=utc)),
        ),
    ]
