# Generated by Django 3.1.2 on 2020-11-22 22:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20201122_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 22, 22, 11, 1, 469789, tzinfo=utc)),
        ),
    ]
